version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  BUILDING_ON_PLATFORM: win
  BuildEnvironment: appveyor
dotnet_csproj:
  patch: true
  file: '**\src\RabbitMQ.EventBus.AspNetCore\RabbitMQ.EventBus.AspNetCore.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  verbosity: minimal
test: off