name: .NET Core

on: [push]

jobs:
  build:

    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
        source-url:: https://api.nuget.org/v3/index.json
    - name: Build with dotnet
      run: dotnet build --configuration Release src/RabbitMQ.EventBus.AspNetCore 
    - name: Pack
      run: dotnet pack src/RabbitMQ.EventBus.AspNetCore -c Release --include-symbols --include-source -o artifacts/
    - name: Publish Symbols to NuGet
      run: dotnet nuget push artifacts/*.symbols.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://www.nuget.org/api/v2/package
